services:
  frontend:
    build:
      context: ./frontend
      target: runner
    volumes:
      - frontend_node_modules:/src/node_modules
      - frontend_next_cache:/src/.next
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
    restart: unless-stopped

  backend:
    build:
      context: ./backend
    volumes:
      - ./frontend/src/app/custom_templates:/app/custom_templates
      - /root/mnt/nifti_filestore:/app/filestore
    environment:
      - FILESTORE_PATH=/app/filestore
      - FLASK_ENV=production
      - SECRET_KEY=${SECRET_KEY:-your-super-secret-production-key-change-this-immediately}
      - DATABASE_URL=${DATABASE_URL:-postgresql://myuser:mypassword@db:5432/brain_dev}
    restart: unless-stopped
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  default:
    name: app-network

volumes:
  frontend_node_modules:
  frontend_next_cache:
