services:
  frontend:
    build:
      context: ./frontend
      target: dev
    volumes:
      - ./frontend:/src
      - frontend_node_modules:/src/node_modules
      - frontend_next_cache:/src/.next
    environment:
      - NODE_ENV=development
    command: ["npm", "run", "dev"]

  backend:
    build:
      context: ./backend
    command: ["flask", "--app", "app:app", "run", "--host=0.0.0.0", "--port=5001"]

volumes:
  frontend_node_modules:
  frontend_next_cache: