services:
  frontend:
    build:
      context: ./frontend
      target: runner
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
    networks:
      - app-network
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    depends_on:
      - db
      - redis
    environment:
      - DATABASE_URL=postgresql://myuser:mypassword@db:5432/brain_dev
      - FILESTORE_PATH=/app/filestore
    ports:
      - "5001:5001"
    volumes:
      - ./frontend/src/app/custom_templates:/app/custom_templates
    networks:
      - app-network

  db:
    image: postgres
    healthcheck:
      disable: true
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: brain_dev
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network

  redis:
    image: redis:latest
    restart: always
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db_data:
