"""initial migration

Revision ID: 6644350424c3
Revises: 
Create Date: 2025-05-12 04:01:08.895334

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6644350424c3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sample_data',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('origin_cancer', sa.String(), nullable=False),
    sa.Column('tumor_count', sa.Integer(), nullable=False),
    sa.Column('tumor_size', sa.String(), nullable=False),
    sa.Column('tumor_location', sa.String(), nullable=False),
    sa.Column('patient_age', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sample_data')
    # ### end Alembic commands ###
