"""create new set of tables

Revision ID: a864e19f8035
Revises: 6644350424c3
Create Date: 2025-06-03 01:24:59.140233

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a864e19f8035'
down_revision = '6644350424c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patients',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('origin_cancer', sa.String(), nullable=False),
    sa.Column('tumor_count', sa.Integer(), nullable=False),
    sa.Column('dob', sa.Date(), nullable=False),
    sa.Column('sex', sa.String(length=10), nullable=False),
    sa.Column('height_cm', sa.Float(), nullable=False),
    sa.Column('weight_kg', sa.Float(), nullable=False),
    sa.Column('systolic_bp', sa.Integer(), nullable=False),
    sa.Column('diastolic_bp', sa.Integer(), nullable=False),
    sa.Column('date_of_original_diagnosis', sa.Date(), nullable=False),
    sa.Column('date_of_metastatic_diagnosis', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('nifti_data',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('series_type', sa.String(), nullable=False),
    sa.CheckConstraint("series_type IN ('tumor_mask', 'dose_mask', 'mri_mask')", name='check_nifti_data_type'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('dose_mask',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('max_dose', sa.Integer(), nullable=False),
    sa.Column('volume_mm3', sa.Float(), nullable=False),
    sa.Column('x_com', sa.Integer(), nullable=False),
    sa.Column('y_com', sa.Integer(), nullable=False),
    sa.Column('z_com', sa.Integer(), nullable=False),
    sa.Column('x_min', sa.Integer(), nullable=False),
    sa.Column('x_max', sa.Integer(), nullable=False),
    sa.Column('y_min', sa.Integer(), nullable=False),
    sa.Column('y_max', sa.Integer(), nullable=False),
    sa.Column('z_min', sa.Integer(), nullable=False),
    sa.Column('z_max', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['nifti_data.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('mri_mask',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('timepoint', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['nifti_data.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('tumor_mask',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('volume_mm3', sa.Float(), nullable=False),
    sa.Column('x_com', sa.Integer(), nullable=False),
    sa.Column('y_com', sa.Integer(), nullable=False),
    sa.Column('z_com', sa.Integer(), nullable=False),
    sa.Column('x_min', sa.Integer(), nullable=False),
    sa.Column('x_max', sa.Integer(), nullable=False),
    sa.Column('y_min', sa.Integer(), nullable=False),
    sa.Column('y_max', sa.Integer(), nullable=False),
    sa.Column('z_min', sa.Integer(), nullable=False),
    sa.Column('z_max', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['nifti_data.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.drop_table('sample_data')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sample_data',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('origin_cancer', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('tumor_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('tumor_size', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('tumor_location', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('patient_age', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='sample_data_pkey')
    )
    op.drop_table('tumor_mask')
    op.drop_table('mri_mask')
    op.drop_table('dose_mask')
    op.drop_table('nifti_data')
    op.drop_table('patients')
    # ### end Alembic commands ###
