name: Deploy to DigitalOcean via rsync

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DO_SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519

      - name: Sync code to droplet
        run: |
          rsync -az --delete \
            -e "ssh -i ~/.ssh/id_ed25519 -o StrictHostKeyChecking=no" \
            ./ \
            root@${{ secrets.DO_DEPLOY_HOST }}:${{ secrets.DO_DEPLOY_PATH }}/

      - name: Upload .env to droplet
        run: |
          ssh -i ~/.ssh/id_ed25519 -o StrictHostKeyChecking=no \
            root@${{ secrets.DO_DEPLOY_HOST }} << 'EOF'
cat > "${{ secrets.DO_DEPLOY_PATH }}/.env" << 'EOV'
${{ secrets.PROD_ENV_FILE }}
EOV
EOF

      - name: Restart services on droplet
        run: |
          ssh -i ~/.ssh/id_ed25519 \
              -o StrictHostKeyChecking=no \
              root@${{ secrets.DO_DEPLOY_HOST }} \
          "cd ${{ secrets.DO_DEPLOY_PATH }} && \
          docker compose -f docker-compose.yml \
                         -f docker-compose.prod.yml \
                         pull 2>/dev/null || true && \
          docker compose -f docker-compose.yml \
                         -f docker-compose.prod.yml \
                         up -d --build"
