name: Deploy to DigitalOcean Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DO_SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519

      - name: Sync code to droplet
        run: |
          rsync -az --delete \
            -e "ssh -i ~/.ssh/id_ed25519 -o StrictHostKeyChecking=no" \
            ./ \
            root@${{ secrets.DO_DEPLOY_HOST }}:${{ secrets.DO_DEPLOY_PATH }}/

      - name: Set production environment variables
        run: |
          ssh -i ~/.ssh/id_ed25519 \
              -o StrictHostKeyChecking=no \
              root@${{ secrets.DO_DEPLOY_HOST }} \
          "cd ${{ secrets.DO_DEPLOY_PATH }} && \
          echo 'SECRET_KEY=${{ secrets.PROD_SECRET_KEY }}' > env.production && \
          echo 'DATABASE_URL=postgresql://myuser:mypassword@db:5432/brain_dev' >> env.production && \
          echo 'FILESTORE_PATH=/app/filestore' >> env.production && \
          echo 'FLASK_ENV=production' >> env.production && \
          echo 'NODE_ENV=production' >> env.production"

      - name: Deploy to production
        run: |
          ssh -i ~/.ssh/id_ed25519 \
              -o StrictHostKeyChecking=no \
              root@${{ secrets.DO_DEPLOY_HOST }} \
          "cd ${{ secrets.DO_DEPLOY_PATH }} && \
          chmod +x deploy_production.sh && \
          ./deploy_production.sh"

      - name: Verify deployment
        run: |
          ssh -i ~/.ssh/id_ed25519 \
              -o StrictHostKeyChecking=no \
              root@${{ secrets.DO_DEPLOY_HOST }} \
          "cd ${{ secrets.DO_DEPLOY_PATH }} && \
          docker compose -f docker-compose.yml -f docker-compose.prod.yml ps"
