name: Deploy to DigitalOcean

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DO_SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H ${{ secrets.DO_DEPLOY_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy via SSH as root
        run: |
          ssh -i ~/.ssh/id_ed25519 root@${{ secrets.DO_DEPLOY_HOST }} << 'EOF'
            set -e
            cd ${{ secrets.DO_DEPLOY_PATH }}
            git fetch --prune
            git checkout main
            git reset --hard origin/main
            docker compose pull
            docker compose up -d --build
          EOF
